fixed assemblies

diff --git a/eldEnv b/eldEnv
--- a/eldEnv
+++ b/eldEnv
@@ -1,7 +1,7 @@
 # Figures out where Eldarica is installed and runs it with the proper classpath
 # (partially copied from the scala dist.)
 SOURCE=$0;
-Z3_LIB_PATH=/home/philipp/tmp/z3/lib
+# Z3_LIB_PATH=/home/philipp/tmp/z3/lib
 SCRIPT=`basename "${SOURCE}"`;
 
 # Finds the root folder of the distribution, through the tempest (and the
@@ -19,7 +19,7 @@ done;
 
 LAZABS_HOME=`dirname "${SOURCE}"`;
 
-export LD_LIBRARY_PATH=${Z3_LIB_PATH}:/usr/local/lib:/usr/local/lib/jni:/usr/lib/jni;
+# export LD_LIBRARY_PATH=${Z3_LIB_PATH}:/usr/local/lib:/usr/local/lib/jni:/usr/lib/jni;
 
 export JAVA_OPTS="-Xmx2024m -Xss20000k";
 
@@ -30,14 +30,12 @@ if [ -f ${LAZABS_HOME}/dist/lazabs.jar ]; then
 
 else if [ -f ${LAZABS_HOME}/target/scala-2.*/Eldarica-assembly*.jar ]; then
 
-        # binary distribution
+        # binary distribution from sbt
 	export LAZABS_CMD="java ${JAVA_OPTS} -cp ${LAZABS_HOME}/target/scala-2.*/Eldarica-assembly*.jar"
 
 else
 
-	# source distribution
-
-	export LAZABS_CP="${LAZABS_HOME}"/dist/lazabs.jar:"${LAZABS_HOME}"/lib/java-cup-11a-runtime.jar:"${LAZABS_HOME}"/lib/z3.jar:"${LAZABS_HOME}"/lib/princess.jar:"${LAZABS_HOME}"/lib/smt-parser.jar:"${LAZABS_HOME}"/lib/tplspec-parser.jar:"${LAZABS_HOME}"/lib/cc-parser.jar:"${LAZABS_HOME}"/flata/flata.jar:"${LAZABS_HOME}"/flata/acceleration.jar:"${LAZABS_HOME}"/flata/glpk-java-4.47.jar:"${LAZABS_HOME}"/lib/antlr-3.3-complete.jar:"${LAZABS_HOME}"/flata/nts.jar:"${LAZABS_HOME}"/bip-lib/*
-	export LAZABS_CMD="scala -cp $LAZABS_CP"
+        echo "Could not find Eldarica jar" >&2
+        exit 1
 
 fi; fi
