update to latest Princess version, which fixes a bug in predicate generation

diff --git a/regression-tests/rundir b/regression-tests/rundir
--- a/regression-tests/rundir
+++ b/regression-tests/rundir
@@ -20,7 +20,10 @@ res=0
 if cmp -s "$DIR"/Answers"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX"; then
     echo -ne "\tSucceeded"
 else
-    echo -ne "\tFAILED"
+    echo -e "\tFAILED"
+    echo
+    diff "$DIR"/Answers"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX" || true
+    echo
     cp "$DIR"/Output"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX"-"`date`"
     res=1
 fi
